{% set name = "finmind" %}
{% set version = "1.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FinMind-{{ version }}.tar.gz
  sha256: 791bcdbcd698d6e424eb69c7b37b8d51adb2e95553e3e6298941f94f55d6a61e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - FinMind

about:
  home: https://github.com/FinMind/FinMind
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "financial mining"
  doc_url: https://linsamtw.github.io/FinMindDoc

extra:
  recipe-maintainers:
    - roccqqck
