{% set name = "finmind" %}
{% set version = "1.0.91" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FinMind-{{ version }}.tar.gz
  sha256: ad8c0ffcb78f2f1ad7e18e56a5d1a8fc1dca58e386f213ecc72f5fd48ccd2235

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - FinMind


about:
  home: https://github.com/FinMind/FinMind
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "financial mining"
  doc_url: https://linsamtw.github.io/FinMindDoc

extra:
  recipe-maintainers:
    - roccqqck
