{% set name = "finmind" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FinMind-{{ version }}.tar.gz
  sha256: 0ecf1c66be735da1761156a78a94dc756a4aa1d8ddf509b8ddfa3a6f7b6c9a15

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - FinMind


about:
  home: https://github.com/FinMind/FinMind
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "financial mining"
  doc_url: https://linsamtw.github.io/FinMindDoc

extra:
  recipe-maintainers:
    - roccqqck
