{% set name = "finmind" %}
{% set version = "1.0.90" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FinMind-{{ version }}.tar.gz
  sha256: acef608a6b126830038cf979648e9e5ab7a3a3ac66b203ff4f1c805d27f926b2

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - FinMind


about:
  home: https://github.com/FinMind/FinMind
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "financial mining"
  doc_url: https://linsamtw.github.io/FinMindDoc

extra:
  recipe-maintainers:
    - roccqqck
