{% set name = "finmind" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FinMind-{{ version }}.tar.gz
  sha256: 5f5919ff7350859b814e4184d502a32827cc30e4618569eae4598f6df33d2797

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - FinMind

about:
  home: https://github.com/FinMind/FinMind
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: financial mining
  doc_url: https://linsamtw.github.io/FinMindDoc

extra:
  recipe-maintainers:
    - roccqqck
